In [1]:
import pandas as pd
import numpy as np

In [2]:
ipl = pd.read_csv('C:/Users/Admin/Downloads/IPL Ball-by-Ball 2008-2020.csv')

In [3]:
ipl

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193463,1237181,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,0,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193464,1237181,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193465,1237181,1,13,1,RR Pant,SS Iyer,KH Pandya,0,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
193466,1237181,1,13,2,RR Pant,SS Iyer,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193467,1237181,1,13,3,SS Iyer,RR Pant,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [4]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193468 entries, 0 to 193467
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                193468 non-null  int64
 1   inning            193468 non-null  int64
 2   over              193468 non-null  int64
 3   ball              193468 non-null  int64
 4   batsman           193468 non-null  object
 5   non_striker       193468 non-null  object
 6   bowler            193468 non-null  object
 7   batsman_runs      193468 non-null  int64
 8   extra_runs        193468 non-null  int64
 9   total_runs        193468 non-null  int64
 10  non_boundary      193468 non-null  int64
 11  is_wicket         193468 non-null  int64
 12  dismissal_kind    9495 non-null    object
 13  player_dismissed  9495 non-null    object
 14  fielder           6784 non-null    object
 15  extras_type       10233 non-null   object
 16  batting_team      193468 non-null  object
 17  bowling_team      193277 non-null  object
dtypes: int64(9), object(9)
memory usage: 26.6+ MB

In [5]:
ipl.isnull().sum()

id                       0
inning                   0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
non_boundary             0
is_wicket                0
dismissal_kind      183973
player_dismissed    183973
fielder             186684
extras_type         183235
batting_team             0
bowling_team           191
dtype: int64

In [6]:
ipl.duplicated().sum()

1

In [7]:
ipl.drop_duplicates(inplace=True)

In [8]:
ipl.batting_team.replace({'Rising Pune Supergiants' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl.batting_team.replace({'Pune Warriors' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl.batting_team.replace({'Delhi Daredevils' : 'Delhi Capitals'},regex=True,inplace=True)

ipl.bowling_team.replace({'Rising Pune Supergiants' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl.bowling_team.replace({'Pune Warriors' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl.bowling_team.replace({'Delhi Daredevils' : 'Delhi Capitals'},regex=True,inplace=True)

In [9]:
ipl.batting_team.value_counts()

batting_team
Mumbai Indians                 24465
Delhi Capitals                 22788
Royal Challengers Bangalore    22706
Kings XI Punjab                22622
Kolkata Knight Riders          22554
Chennai Super Kings            21455
Rajasthan Royals               18954
Sunrisers Hyderabad            14826
Deccan Chargers                 9034
Rising Pune Supergiant          8923
Gujarat Lions                   3558
Kochi Tuskers Kerala            1582
Name: count, dtype: int64

In [10]:
ipl.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [11]:
ipl.drop(columns=['non_striker','non_boundary','dismissal_kind','player_dismissed','fielder','extras_type'],axis=1,inplace=True)

In [12]:
ipl.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'bowler', 'batsman_runs',
       'extra_runs', 'total_runs', 'is_wicket', 'batting_team',
       'bowling_team'],
      dtype='object')

In [13]:
ipl.replace('Bangalore','Bengaluru', inplace = True)

In [14]:
ipl.isnull().sum()

id                0
inning            0
over              0
ball              0
batsman           0
bowler            0
batsman_runs      0
extra_runs        0
total_runs        0
is_wicket         0
batting_team      0
bowling_team    191
dtype: int64

In [15]:
ipl.bowling_team.isnull().sum()

191

In [16]:
pune = ipl['id']==50126
royal = ipl['id']==829763
ipl['bowling_team'].loc[pune]=ipl['bowling_team'].loc[pune].fillna('Rising Pune Supergiant')
ipl['bowling_team'].loc[royal]=ipl['bowling_team'].loc[royal].fillna('Rajasthan Royals')

# df['A'].loc[condition] = df['A'].loc[condition].fillna(99)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12204\1663445294.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipl['bowling_team'].loc[pune]=ipl['bowling_team'].loc[pune].fillna('Rising Pune Supergiant')
C:\Users\Admin\AppData\Local\Temp\ipykernel_12204\1663445294.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipl['bowling_team'].loc[royal]=ipl['bowling_team'].loc[royal].fillna('Rajasthan Royals')

In [17]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193467 entries, 0 to 193467
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            193467 non-null  int64
 1   inning        193467 non-null  int64
 2   over          193467 non-null  int64
 3   ball          193467 non-null  int64
 4   batsman       193467 non-null  object
 5   bowler        193467 non-null  object
 6   batsman_runs  193467 non-null  int64
 7   extra_runs    193467 non-null  int64
 8   total_runs    193467 non-null  int64
 9   is_wicket     193467 non-null  int64
 10  batting_team  193467 non-null  object
 11  bowling_team  193404 non-null  object
dtypes: int64(8), object(4)
memory usage: 19.2+ MB

# Matches dataset

In [18]:
ipl1 = pd.read_csv('C:/Users/Admin/Downloads/IPL Matches 2008-2020.csv')
ipl1

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [19]:
ipl1.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [20]:
ipl1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [21]:
ipl1['result'].value_counts()

result
wickets    435
runs       364
tie         13
Name: count, dtype: int64

In [22]:
ipl1['loser_team'] = ipl1.apply(lambda row: row['team2'] if row['team1'] == row['winner'] else row['team1'], axis=1)

# If you want to remove matches with 'no result' or 'abandoned' from the DataFrame, you can do this:
ipl1 = ipl1[ipl1['result'] != 'no result']
ipl1 = ipl1[ipl1['result'] != 'abandoned']

# Reset the DataFrame index
ipl1.reset_index(drop=True, inplace=True)

# Display the DataFrame with the 'loser_team' column
ipl1

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,loser_team
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen,Royal Challengers Bangalore
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri,Kings XI Punjab
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar,Rajasthan Royals
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper,Mumbai Indians
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan,Deccan Chargers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel,Mumbai Indians
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon,Delhi Capitals
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi,Royal Challengers Bangalore
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi,Sunrisers Hyderabad
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon,Delhi Capitals

In [23]:
ipl1.winner.value_counts()

winner
Mumbai Indians                 120
Chennai Super Kings            106
Kolkata Knight Riders           99
Royal Challengers Bangalore     91
Kings XI Punjab                 88
Rajasthan Royals                81
Delhi Daredevils                67
Sunrisers Hyderabad             66
Deccan Chargers                 29
Delhi Capitals                  19
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [24]:
ipl1.team1.replace({'Rising Pune Supergiants' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.team1.replace({'Pune Warriors' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.team1.replace({'Delhi Daredevils' : 'Delhi Capitals'},regex=True,inplace=True)

ipl1.team2.replace({'Rising Pune Supergiants' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.team2.replace({'Pune Warriors' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.team2.replace({'Delhi Daredevils' : 'Delhi Capitals'},regex=True,inplace=True)

ipl1.winner.replace({'Rising Pune Supergiants' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.winner.replace({'Pune Warriors' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.winner.replace({'Delhi Daredevils' : 'Delhi Capitals'},regex=True,inplace=True)

ipl1.toss_winner.replace({'Rising Pune Supergiants' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.toss_winner.replace({'Pune Warriors' : 'Rising Pune Supergiant'},regex=True,inplace=True)
ipl1.toss_winner.replace({'Delhi Daredevils' : 'Delhi Capitals'},regex=True,inplace=True)

In [25]:
ipl1.winner.unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Capitals',
       'Royal Challengers Bangalore', 'Rajasthan Royals',
       'Kings XI Punjab', 'Deccan Chargers', 'Mumbai Indians',
       'Rising Pune Supergiant', 'Kochi Tuskers Kerala', nan,
       'Sunrisers Hyderabad', 'Gujarat Lions'], dtype=object)

In [26]:
ipl1.venue.replace({'Feroz Shah Kotla Ground':'Feroz Shah Kotla',
                    'M Chinnaswamy Stadium':'M. Chinnaswamy Stadium',
                    'MA Chidambaram Stadium, Chepauk':'M.A. Chidambaram Stadium',
                     'M. A. Chidambaram Stadium':'M.A. Chidambaram Stadium',
                     'Punjab Cricket Association IS Bindra Stadium, Mohali':'Punjab Cricket Association Stadium',
                     'Punjab Cricket Association Stadium, Mohali':'Punjab Cricket Association Stadium',
                     'IS Bindra Stadium':'Punjab Cricket Association Stadium',
                    'Rajiv Gandhi International Stadium, Uppal':'Rajiv Gandhi International Stadium',
                    'Rajiv Gandhi Intl. Cricket Stadium':'Rajiv Gandhi International Stadium'},regex=True,inplace=True)

In [27]:
ipl1.venue.value_counts()

venue
Eden Gardens                                           77
Feroz Shah Kotla                                       74
Wankhede Stadium                                       73
M. Chinnaswamy Stadium                                 65
Rajiv Gandhi International Stadium                     64
M.A. Chidambaram Stadium                               57
Punjab Cricket Association Stadium                     56
Sawai Mansingh Stadium                                 47
Dubai International Cricket Stadium                    33
Sheikh Zayed Stadium                                   29
Maharashtra Cricket Association Stadium                21
Sharjah Cricket Stadium                                18
Dr DY Patil Sports Academy                             17
Subrata Roy Sahara Stadium                             17
M.Chinnaswamy Stadium                                  15
Kingsmead                                              15
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium    13
Sardar Patel Stadium, Motera                           12
SuperSport Park                                        12
Brabourne Stadium                                      11
Saurashtra Cricket Association Stadium                 10
Himachal Pradesh Cricket Association Stadium            9
Holkar Cricket Stadium                                  9
New Wanderers Stadium                                   8
Newlands                                                7
Barabati Stadium                                        7
JSCA International Stadium Complex                      7
St George's Park                                        7
Shaheed Veer Narayan Singh International Stadium        6
Nehru Stadium                                           5
Green Park                                              4
De Beers Diamond Oval                                   3
Vidarbha Cricket Association Stadium, Jamtha            3
Buffalo Park                                            3
OUTsurance Oval                                         2
Name: count, dtype: int64

In [28]:
ipl1.replace('Bangalore','Bengaluru', inplace = True)

In [29]:
#fill missing values

ipl1['city'].fillna(ipl1['venue'], inplace = True)
ipl1['winner'].fillna(ipl1['result'], inplace = True)
ipl1['player_of_match'].fillna(ipl1['result'], inplace = True)

In [30]:
ipl1.isnull().sum()

id                   0
city                 0
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
loser_team           0
dtype: int64

In [31]:
ipl1.isnull().sum()

id                   0
city                 0
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
loser_team           0
dtype: int64

In [32]:
ipl1['result_margin'].fillna(ipl1['result_margin'].mean(),inplace=True)

In [33]:
ipl1.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2',
       'loser_team'],
      dtype='object')

In [34]:
ipl1.drop(columns=['method','neutral_venue','eliminator','umpire1','umpire2'],axis=1,inplace=True)

In [35]:
# ipl1.dropna(subset=['winner'],inplace=True)

In [36]:
ipl1.isnull().sum()

id                 0
city               0
date               0
player_of_match    4
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             4
result             4
result_margin      0
loser_team         0
dtype: int64

In [37]:
ipl1['season']=pd.DatetimeIndex(ipl1['date']).year

In [38]:
ipl1.head(3)

,id,city,date,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,loser_team,season
0,335982,Bengaluru,2008-04-18,BB McCullum,M. Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Royal Challengers Bangalore,2008
1,335983,Chandigarh,2008-04-19,MEK Hussey,Punjab Cricket Association Stadium,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,Kings XI Punjab,2008
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,Rajasthan Royals,2008

In [39]:
ipl1.winner.value_counts()

winner
Mumbai Indians                 120
Chennai Super Kings            106
Kolkata Knight Riders           99
Royal Challengers Bangalore     91
Kings XI Punjab                 88
Delhi Capitals                  86
Rajasthan Royals                81
Sunrisers Hyderabad             66
Deccan Chargers                 29
Rising Pune Supergiant          27
Gujarat Lions                   13
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [40]:
ipl1.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin',
       'loser_team', 'season'],
      dtype='object')

In [43]:
ipl.dropna(inplace=True)

In [47]:
ipl1.dropna(inplace=True)

In [48]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193404 entries, 0 to 193467
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            193404 non-null  int64
 1   inning        193404 non-null  int64
 2   over          193404 non-null  int64
 3   ball          193404 non-null  int64
 4   batsman       193404 non-null  object
 5   bowler        193404 non-null  object
 6   batsman_runs  193404 non-null  int64
 7   extra_runs    193404 non-null  int64
 8   total_runs    193404 non-null  int64
 9   is_wicket     193404 non-null  int64
 10  batting_team  193404 non-null  object
 11  bowling_team  193404 non-null  object
dtypes: int64(8), object(4)
memory usage: 19.2+ MB

In [49]:
ipl1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 812 entries, 0 to 815
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               812 non-null    int64
 1   city             812 non-null    object
 2   date             812 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            812 non-null    object
 5   team1            812 non-null    object
 6   team2            812 non-null    object
 7   toss_winner      812 non-null    object
 8   toss_decision    812 non-null    object
 9   winner           812 non-null    object
 10  result           812 non-null    object
 11  result_margin    812 non-null    float64
 12  loser_team       812 non-null    object
 13  season           812 non-null    int32
dtypes: float64(1), int32(1), int64(1), object(11)
memory usage: 92.0+ KB

In [51]:
ipl.to_csv('IPL Ball-by=Ball.csv',index=False)
ipl1.to_csv('IPL Match-08-20.csv',index=False)